package com.equo.comm.api.error;

/**
 * This class is intended to be extended by user applications.
 * 
 * <p>Any {@code CommMessageException} will be catched by the Comm Service and
 * communicate the error.
 */
public class CommMessageException extends RuntimeException {

  /**
   * Generated by eclipse.
   */
  private static final long serialVersionUID = -4576317942191172357L;

  private int errorCode;

  public CommMessageException(int errorCode, String errorMessage) {
    super(errorMessage);
    this.errorCode = errorCode;
  }

  @Override
  public Throwable fillInStackTrace() {
    return this;
  }

  public int getErrorCode() {
    return errorCode;
  }
}
